# Generated by Django 4.2.3 on 2023-07-27 11:24

from django.db import migrations, models
import ultils.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m', validators=[ultils.model_validators.validator_png]),
        ),
    ]
